Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/js/utils.js
Not Found: /static/debug_toolbar/css/toolbar.css
Not Found: /static/debug_toolbar/js/toolbar.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/images/favicon.png
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/css/toolbar.css
Not Found: /static/debug_toolbar/css/toolbar.css
Not Found: /static/debug_toolbar/js/toolbar.js
Not Found: /static/debug_toolbar/css/print.css
Not Found: /static/debug_toolbar/css/toolbar.css
Not Found: /static/debug_toolbar/js/toolbar.js
Not Found: /static/debug_toolbar/css/print.css
Internal Server Error: /6abeed28-b79e-4697-8d6e-5a22785b6889/update/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/code/books/views.py", line 75, in form_valid
    if form.instance.title == '' or form.instance.titl is None:
AttributeError: 'Book' object has no attribute 'titl'
Not Found: /favicon.ico/
